## Configuration

Follow instruction given from github repo to see something similar like below:

```
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<COS API KEY>',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
    config=Config(signature_version='oauth'),
    endpoint_url='<COS ENDPOINT>')

bucket = '<COS BUCKET NAME>'
object_key = 'data_api_ws.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_1 = pd.read_csv(body, sep=";")
df_1.head(10)
```

In [1]:
# Insert data that you have uploaded in this cell
# Refer to previous markdown to see sample of generated code

,request id,api code,time of call,api call duration,status
0,024aae60-1a81-3f37-bbe6-3f832c919706,A1,01-02-2025 00:00:00,7.010387,success
1,028d67dd-c6d0-329f-a20e-78db9eab7a55,A3,01-02-2025 00:17:00,51.419393,success
2,02d12bf9-5fe2-3d0c-b233-30e02224b686,A3,01-02-2025 00:19:09,25.860775,success
3,0b3aee1e-dc3b-3728-bc55-f57a23446b3d,A8,01-02-2025 00:37:04,0.205909,success
4,0dbfffb4-3ed4-3cb2-904d-c348501a996e,A8,01-02-2025 00:47:07,0.122125,failed
5,16fdcdc8-702d-381b-af47-73af6de0750a,A8,01-02-2025 00:50:03,15.326789,success
6,200811cc-f582-31e3-9c06-3e1b3e45c70f,A4,01-02-2025 00:54:19,0.401190,success
7,212b75e4-4eab-333e-a0c9-97b30009e4d9,A1,01-02-2025 00:58:01,15.913862,success
8,2319e7e0-6480-3fd7-9408-46a976d34436,A6,01-02-2025 01:15:10,0.005437,failed
9,23b30eea-06c7-3576-bb6e-09df0fea6a9d,A6,01-02-2025 01:24:00,17.533400,success

In [17]:
ibm_api_key_id='<API KEY retrieved from previous cell>'
endpoint_url='<ENDPOINT retrieved from previous cell>'
bucket_name = '<BUCKET NAME retrieved from previous cell>'
object_key = '<File Name for the upl>'

In [18]:
def query_api_data(sql_query):
    import sqlite3
    import pandas as pd

    import os, types
    import pandas as pd
    from botocore.client import Config
    import ibm_boto3
    
    def __iter__(self): return 0
    
    # @hidden_cell
    # The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
    # You might want to remove those credentials before you share the notebook.
    
    cos_client = ibm_boto3.client(service_name='s3',
        ibm_api_key_id=ibm_api_key_id,
        ibm_auth_endpoint="https://iam.cloud.ibm.com/identity/token",
        config=Config(signature_version='oauth'),
        endpoint_url=endpoint_url)
    
    bucket = bucket_name
    
    body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
    # add missing __iter__ method, so pandas accepts body as file-like object
    if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
    
    df_1 = pd.read_csv(body, sep=';')
    
    # Create in-memory SQLite database
    conn = sqlite3.connect(':memory:')
    
    # Write DataFrame to SQL table
    df_1.to_sql('data_api_ws', conn, index=False, if_exists='replace')
    
    # Query it
    result = pd.read_sql_query(sql_query, conn)
    
    conn.close()

    return result.to_dict(orient='records')

In [19]:
sql_query = "SELECT `request id` FROM data_api_ws LIMIT 3"

In [20]:
query_api_data(sql_query)

[{'request id': '024aae60-1a81-3f37-bbe6-3f832c919706'},
 {'request id': '028d67dd-c6d0-329f-a20e-78db9eab7a55'},
 {'request id': '02d12bf9-5fe2-3d0c-b233-30e02224b686'}]

In [21]:
print()